version: "3.9"

services:
  holy-unblocker:
    image: quiteafancyemerald/holy-unblocker:6.9.3
    build: .
    container_name: holy-unblocker
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      NODE_ENV: production
